package view;

public class TelaMenu extends javax.swing.JFrame {

   
    
    public TelaMenu() {

        initComponents();
        aplicarPermissoes();
        ajustarTela();
    }
    
    private void aplicarPermissoes() {
        
    }

    private void ajustarTela() {
        getContentPane().setBackground(new java.awt.Color(245, 248, 252));
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(210, 44);
        btnPacientes.setPreferredSize(tamanhoBotao);
        btnProdutos.setPreferredSize(tamanhoBotao);
        btnFornecedor.setPreferredSize(tamanhoBotao);
        btnConsultas.setPreferredSize(tamanhoBotao);
        btnTratamentos.setPreferredSize(tamanhoBotao);
        btnDentistas.setPreferredSize(tamanhoBotao);
        setMinimumSize(new java.awt.Dimension(680, 430));
        setSize(680, 430);
        setResizable(false);
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnPacientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnTratamentos = new javax.swing.JButton();
        btnDentistas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("MENU PRINCIPAL");

        btnPacientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPacientes.setForeground(new java.awt.Color(0, 51, 204));
        btnPacientes.setText("PACIENTES");
        btnPacientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });

        btnProdutos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProdutos.setForeground(new java.awt.Color(0, 51, 204));
        btnProdutos.setText("PRODUTOS");
        btnProdutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFornecedor.setForeground(new java.awt.Color(0, 51, 204));
        btnFornecedor.setText("FORNECEDORES");
        btnFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnConsultas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(0, 51, 204));
        btnConsultas.setText("CONSULTAS");
        btnConsultas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnTratamentos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTratamentos.setForeground(new java.awt.Color(0, 51, 204));
        btnTratamentos.setText("TRATAMENTO");
        btnTratamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTratamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamentosActionPerformed(evt);
            }
        });

        btnDentistas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDentistas.setForeground(new java.awt.Color(0, 51, 204));
        btnDentistas.setText("DENTISTAS");
        btnDentistas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDentistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTratamentos)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDentistas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFornecedor)
                    .addComponent(btnTratamentos)
                    .addComponent(btnConsultas))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutos)
                    .addComponent(btnPacientes)
                    .addComponent(btnDentistas))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
       TelaPacientes t = new TelaPacientes();
       t.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        new TelaAgenda().setVisible(true);
            dispose();
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        new TelaProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnTratamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamentosActionPerformed
        new TelaTratamentos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTratamentosActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        new TelaFornecedores().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnDentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDentistasActionPerformed
        new TelaDentistas().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDentistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDentistas;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnTratamentos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
